account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/',views.login, name='login'),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

pizarra/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
]

project/urls.py
from django.urls import path

from . import views

app_name = 'project'

urlpatterns = [
    path('',views.projects, name='projects'),
    path('add/',views.add, name='add'),
    path('<uuid:pk>/',views.project, name='project'),
    path('<uuid:pk>/edit/',views.edit, name='edit'),
    path('<uuid:pk>/delete/',views.delete, name='delete'),
]

todolist/urls.py
from django.urls import path

from . import views

app_name = 'todolist'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.todolist, name='todolist'),
]

account/models.py
from typing import Any
import uuid

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.db import models

class CustomUserManager(UserManager):
    def _create_user_(self, name, email, password, **extra_fields):
        if not email:
            raise ValueError("You did not provide an valid e-mail address")
        email = self.normalize_email(email)
        user = self.model(email=email, name=name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user
    
    def create_user(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user_(name, email, password, **extra_fields)

    def create_superuser(self,name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user_(name, email, password, **extra_fields)
    

class User(AbstractBaseUser, PermissionsMixin):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=255, blank=True, null=True)

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['name',]

core/models.py
from django.db import models

# Create your models here.

project/models.py
import uuid
from django.db import models

from account.models import User

class Project(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='projects', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

todolist/models.py
import uuid

from django.db import models

from account.models import User
from project.models import Project


class Todolist(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Project, related_name='todolists', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='todolists', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

account/views.py
from django.contrib.auth import authenticate, login as auth_login
from django.shortcuts import render, redirect

from .models import User

def login(request):
    if request.method == 'POST':
        email = request.POST.get('email', '')
        password = request.POST.get('password', '')

        if email and password:
            user = authenticate(request, email=email, password=password)
            if user is not None:
                auth_login(request, user)

                return redirect('/')
    return render(request, 'account/login.html')

def signup(request):
    if request.method == 'POST':
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        password1 = request.POST.get('password1', '')
        password2 = request.POST.get('password2', '')

        if name and email and password1 and password2:
            user = User.objects.create_user(name, email, password1)

            print('User created: ', user)
            
            return redirect('/login/')
        else:
            print('Something went wrong')
    else:
        print('Just show the form!')
    return render(request, 'account/signup.html')

core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html')

def about(request):
    return render(request, 'core/about.html')

project/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .models import Project

#@login_required
def projects(request):
    projects = Project.objects.filter(created_by=request.user)
    return render(request, 'project/projects.html', {
        'projects': projects
    })

#@login_required
def project(request, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=pk)

    return render(request, 'projetct/project.html', {
        'project': project
    })

#@login_required
def add(request):
    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        if name:
            Project.objects.create(name=name, description=description, created_by=request.user)

            return redirect('/projects/')
        else:
            print('Not valid')

    return render(request, 'project/add.html')

#@login_required
def edit(request, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=pk)

    if request.mothod == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        if  name:
            project.name = name
            project.description = description
            project.save()

            return redirect('/projects/')
    return render(request, 'project/edit.html', {
        'project': project
    })

#@login_required
def delete(request, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=pk)
    project.delete()

    return redirect('/projects/')

todolist/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .models import Todolist
from project.models import Project

@login_required
def todolist(request, project_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=pk)

    return render(request, 'todolist/todolist.html', {
        'project': project,
        'todolist': todolist
    })

@login_required
def add(request, project_id):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    
    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        if name:
            Todolist.objects.create(project=project, name=name, description=description, created_by=request.user)

            return redirect(f'/projects/{project_id}')

    return render(request, 'todolist/add.html', {
        'project': project
    })

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="text-3xl">About</h1>

    <div class="mt-6 space-y-6">
        <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis vero saepe aspernatur! Ut veritatis architecto laborum saepe possimus incidunt iusto.
        </p>

        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate soluta necessitatibus error consequatur quia minus doloremque aliquid facere nihil rerum!
        </p>
    </div>

{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Document</title>
</head>
<body>
    <nav class="py-6 px-8 flex items-center justify-between bg-slate-800">
        <h1 class="text-xl text-white"><a href="{% url 'core:index' %}">Pizarra</a></h1>

        <div class="space-x-4">
            <a href="{% url 'core:about' %}" class="text-white">About</a>

            {% if request.user.is_authenticated %}
                <a href="{% url 'project:projects' %}" class="py-4 px-8 bg-sky-600 text-white">Projects</a>
            {% else %}
                <a href="{% url 'account:login' %}" class="py-4 px-8 bg-slate-600 text-white">Login in</a>
                <a href="{% url 'account:signup' %}" class="py-4 px-8 bg-sky-600 text-white">Sign up</a>
            {% endif %}
        </div>
    </nav>

    <main class="py-6 px-8">
        {% block content %}
        {% endblock %}
    </main>

    <footer class="py-8 px-8 bg-slate-900 text-center">
        <p class="text-white">Copyright (c) 2024 - Pizarra</p>
    </footer>
</body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}
<header class="py-12 text-center bg-slate-200">
    <h1 class="text-3xl">Welcome tp Pizarra</h1>
</header>
{% endblock %}

project/templates/project/add.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">Add Projects</h1>

    <form action="." class="mt-6 space-y-4" method="post">
        {% csrf_token %}

        <div>
            <label>Name</label><br>
            <input type="text" name="name" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        
        <div>
            <label>Description</label><br>
            <textarea type="text" name="description" class="w-full py-4 px-6 bg-slate-500 text-white"></textarea>
        </div>

        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
        </div>
    </form>

{% endblock %}

project/templates/project/edit.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">Edit project</h1>

    <form action="." method="post" class="mt-6 space-y-4">
        {% csrf_token %}

        <div>
            <label for="">Name</label><br>
            <input type="text" name="name" value="{{ project.name }}" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <label>Description</label><br>
            <textarea name="description" class="w-full py-4 px-6 bg-slate-500 text-white" cols="30" rows="10">{{ project.description }}</textarea>
        </div>

        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
        </div>
    </form>

{% endblock content %}

project/templates/project/project.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">{{ project.name }}</h1>

    <a href="{% url 'todolist:add' project.id %}" class="py-4 px-8 bg-emerald-600 text-white inline-block">Add todolist</a>
    <a href="{% url 'project:edit' project.id %}" class="py-4 px-8 bg-sky-600 text-white inline-block">Edit</a>
    <a href="{% url 'project:delete' project.id %}" class="py-4 px-8 bg-amber-600 text-white inline-block">Delete</a>

    <div class="mt-6 grid grid-cols-4 gap-4">
        {% for todolist in project.todolists.all %}
            <div class="py-6 px-6 bg-slate-200">
                <a href="{% url 'todolist:todolist' project.id todolist.id %}">
                    <h2 class="mb-4 text-xl">{{todolist.name }}</h2>

                    <p class="text-sm text-slate-600">
                        {{ todolist.description }}
                    </p>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

project/templates/project/projects.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">Projects</h1>

    <a href="{% url 'project:add' %}" class="py-4 px-8 bg-sky-600 text-white inline-block">Add project</a>

    <div class="mt-6 grid grid-cols-4 gap-4">
        {% for project in projects %}
            <div class="py-6 px-6 bg-slate-200">
                <a href="{% url 'project:project' project.id %}">
                    <h2 class="mb-4 text-xl">{{ project.name }}</h2>

                    <p class="text-sm text-slate-600">
                        {{ project.description }}
                    </p>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

todolist/templates/todolist/add.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">Add Todolist</h1>

    <form action="." class="mt-6 space-y-4" method="post">
        {% csrf_token %}

        <div>
            <label>Name</label><br>
            <input type="text" name="name" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        
        <div>
            <label>Description</label><br>
            <textarea type="text" name="description" class="w-full py-4 px-6 bg-slate-500 text-white"></textarea>
        </div>

        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
        </div>
    </form>

{% endblock %}

todolist/templates/todolist/todolist.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">{{ todolist.name }}</h1>

    <a href="{% url 'task:add' project.id todolist.id %}" class="py-4 px-8 bg-emerald-600 text-white inline-block">Add task</a>
    <a href="{% url 'todolist:edit' project.id todolist.id %}" class="py-4 px-8 bg-sky-600 text-white inline-block">Edit</a>
    <a href="{% url 'todolist:delete' project.id todolist.id %}" class="py-4 px-8 bg-amber-600 text-white inline-block">Delete</a>

    <div class="mt-6 grid grid-cols-4 gap-4">
        {% for task in todolist.task.all %}
            <div class="py-6 px-6 bg-slate-200">
                <a href="{% url 'task:detail' todolist.project.id todolist.id task.id %}">
                    <h2 class="mb-4 text-xl">{{task.name }}</h2>

                    <p class="text-sm text-slate-600">
                        {{ task.description }}
                    </p>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}